Added Graham to table!
devsontiktok/awesome-devs-on-tiktok pull request #9
Opened 2020-11-15 23:16 UTC by Gbillington1

Hey! I'm Graham and I make tech videos on TikTok. I added myself to the table!

2020-11-16 03:06 UTC, devsontiktok requested changes

2020-11-16 03:06 UTC, devsontiktok commented on README.md
> +| Graham | Coding humor / learning to code / exploring tech | [@grahambillington](https://www.tiktok.com/@grahambillington) | [Twitter](https://twitter.com/GBillington7), [Insta](https://www.instagra
Hey can you pick just one social link for the last column? That'll keep it consistent!

2020-11-16 03:12 UTC, devsontiktok commented
Hey super glad to see you on the list! Just update to one social link and we'll be gtg. If you want to just comment and tell me what link you want I can merge and make the update too if thats easier.

Get the word out! Feel free to make a video or anything else about it. It would be great to see the list keep growing!

2020-11-17 01:45 UTC, merged

2020-11-17 02:49 UTC, Gbillington1 commented
Just saw this, if you could remove the Instagram link that would be great! Thanks